// Ports of local demos and streams, generated by `nimbledeck run` into public/nimbledeck.json.
export interface NimbleConfig { demos: Record<string, { port: number }>; streams: Record<string, { port: number }>; runner?: { port: number; token: string } | null }

let cached: Promise<NimbleConfig> | null = null
export function useNimbleConfig(): Promise<NimbleConfig> {
  cached ??= fetch(`${import.meta.env.BASE_URL}nimbledeck.json`)
    .then((r) => (r.ok ? r.json() : { demos: {}, streams: {} }))
    .catch(() => ({ demos: {}, streams: {} }))
  return cached
}

// Read a theme token, e.g. cssVar('--nd-ink') -> "#1f2328".
export function cssVar(name: string, fallback = '#000'): string {
  return getComputedStyle(document.documentElement).getPropertyValue(name).trim() || fallback
}
